name: smartparking-backend
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
      - flask==2.3.3
      - flask-cors==4.0.0
      - firebase-admin==6.2.0
      - bcrypt==4.0.1
      - PyJWT==2.8.0
      - python-dotenv==1.0.0
      - requests==2.31.0
